#!name=Apple WLOC 定位修改 (纯本地版)
#!desc=修改 Apple 网络定位返回坐标（已本地化）| 选点网页: https://yjtdw.github.io/my-shadowrocket-rules/ | 定位键: https://www.icloud.com/shortcuts/2a811c3bac0e4694b1875ae45b26ab0d | 恢复键: https://www.icloud.com/shortcuts/9092b1a576cf4b7c8bc0dd931ba512a6
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=wloc.js
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
